version: "3.9"
services:
        grobid:
                image: lfoppiano/grobid:0.7.2-SNAPSHOT
                ports:
                        - "8070:8070"
                        - "8071:8071"
                expose:
                        - "8070"
                        - "8071"
                network_mode: host
        app:
                build: .
                depends_on:
                   - grobid
                network_mode: host
                command: ["wait4x", "http", "http://localhost:8070/api/isalive","-t","600s","-i","5s","--expect-status-code","200","--expect-body-regex","^true$$","--", "python","extract_academic_pdf_text.py"]